export const products = [
  {
    id: 1,
    title: "Heraldo road to inmortal, support 4",
    price: "$20",
    stock: 1000,
    description: "Guia para dejar de ser heraldo y ser un mejor player ",
    category: "pos 4",
    img: "https://media.esportsedition.com/wp-content/uploads/2019/01/herald.png",
  },
  {
    id: 2,
    title: "Heraldo road to inmortal, support 5 ",
    price: "$20",
    stock: 1000,
    description: "Guia para dejar de ser heraldo y ser un mejor player ",
    category: "pos 4",
    img: "https://media.esportsedition.com/wp-content/uploads/2019/01/herald.png",
  },
  {
    id: 3,
    title: "Heraldo road to inmortal, OffLane 3",
    price: "$20",
    stock: 1000,
    description: "Guia para dejar de ser heraldo y ser un mejor player ",
    category: "Noticias",
    img: "https://media.esportsedition.com/wp-content/uploads/2019/01/herald.png",
  },
  {
    id: 4,
    title: "Heraldo road to inmortal, Midlane 2",
    price: "$20",
    stock: 1000,
    description: "Guia para dejar de ser heraldo y ser un mejor player ",
    category: "Estadisticas",
    img: "https://media.esportsedition.com/wp-content/uploads/2019/01/herald.png",
  },
];
